create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique not null,
    display_name text,
    role text not null default 'miembro' check (role in ('tesorero', 'miembro')),
    created_at timestamptz not null default now()
);

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text unique,
    course text,
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.fees (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    month int not null check (month between 1 and 12),
    year int not null check (year >= 2024),
    amount numeric(10,2) not null check (amount > 0),
    created_at timestamptz not null default now(),
    unique (student_id, month, year)
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    fee_id bigint not null references public.fees(id) on delete cascade,
    amount_paid numeric(10,2) not null check (amount_paid > 0),
    paid_at date not null,
    payment_method text,
    note text,
    created_at timestamptz not null default now()
);

create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    concept text not null,
    amount numeric(10,2) not null check (amount > 0),
    spent_at date not null,
    description text,
    created_at timestamptz not null default now()
);

create table if not exists public.income_entries (
    id bigint generated by default as identity primary key,
    source text not null,
    amount numeric(10,2) not null check (amount > 0),
    received_at date not null,
    description text,
    created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email, display_name)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
    )
    on conflict (id) do update
    set email = excluded.email;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_treasurer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid() and role = 'tesorero'
    );
$$;

create or replace function public.get_course_financial_summary()
returns table (
    total_fee_payments numeric,
    total_extra_income numeric,
    total_income numeric,
    total_course_debt numeric,
    total_expenses numeric,
    current_balance numeric
)
language sql
stable
security definer
set search_path = public
as $$
    with payment_totals as (
        select
            fee_id,
            coalesce(sum(amount_paid), 0)::numeric as paid_total
        from public.payments
        group by fee_id
    ),
    fee_debt as (
        select
            coalesce(sum(greatest(f.amount - coalesce(pt.paid_total, 0), 0)), 0)::numeric as total_course_debt
        from public.fees f
        left join payment_totals pt on pt.fee_id = f.id
    )
    select
        coalesce((select sum(amount_paid) from public.payments), 0)::numeric as total_fee_payments,
        coalesce((select sum(amount) from public.income_entries), 0)::numeric as total_extra_income,
        (
            coalesce((select sum(amount_paid) from public.payments), 0)
            + coalesce((select sum(amount) from public.income_entries), 0)
        )::numeric as total_income,
        (select total_course_debt from fee_debt),
        coalesce((select sum(amount) from public.expenses), 0)::numeric as total_expenses,
        (
            coalesce((select sum(amount_paid) from public.payments), 0)
            + coalesce((select sum(amount) from public.income_entries), 0)
            - coalesce((select sum(amount) from public.expenses), 0)
        )::numeric as current_balance;
$$;

grant execute on function public.is_treasurer() to anon, authenticated;
grant execute on function public.get_course_financial_summary() to authenticated;

alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.fees enable row level security;
alter table public.payments enable row level security;
alter table public.expenses enable row level security;
alter table public.income_entries enable row level security;

drop policy if exists "profiles read own" on public.profiles;
create policy "profiles read own"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "students public read" on public.students;
drop policy if exists "students own read" on public.students;
create policy "students own read"
on public.students for select
to authenticated
using (
    (select public.is_treasurer())
    or lower(coalesce(email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "fees public read" on public.fees;
drop policy if exists "fees own read" on public.fees;
create policy "fees own read"
on public.fees for select
to authenticated
using (
    (select public.is_treasurer())
    or exists (
        select 1
        from public.students s
        where s.id = fees.student_id
        and lower(coalesce(s.email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
);

drop policy if exists "payments public read" on public.payments;
drop policy if exists "payments own read" on public.payments;
create policy "payments own read"
on public.payments for select
to authenticated
using (
    (select public.is_treasurer())
    or exists (
        select 1
        from public.fees f
        join public.students s on s.id = f.student_id
        where f.id = payments.fee_id
        and lower(coalesce(s.email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
    )
);

drop policy if exists "expenses public read" on public.expenses;
drop policy if exists "expenses authenticated read" on public.expenses;
drop policy if exists "expenses treasurer read" on public.expenses;
create policy "expenses authenticated read"
on public.expenses for select
to authenticated
using (true);

drop policy if exists "income entries authenticated read" on public.income_entries;
drop policy if exists "income entries public read" on public.income_entries;
create policy "income entries authenticated read"
on public.income_entries for select
to authenticated
using (true);

drop policy if exists "treasurer manage students" on public.students;
create policy "treasurer manage students"
on public.students for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

drop policy if exists "treasurer manage fees" on public.fees;
create policy "treasurer manage fees"
on public.fees for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

drop policy if exists "treasurer manage payments" on public.payments;
create policy "treasurer manage payments"
on public.payments for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

drop policy if exists "treasurer manage expenses" on public.expenses;
create policy "treasurer manage expenses"
on public.expenses for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

drop policy if exists "treasurer manage income entries" on public.income_entries;
create policy "treasurer manage income entries"
on public.income_entries for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

create index if not exists idx_fees_student_id on public.fees(student_id);
create index if not exists idx_payments_fee_id on public.payments(fee_id);
create index if not exists idx_income_entries_received_at on public.income_entries(received_at);
