create table if not exists public.income_entries (
    id bigint generated by default as identity primary key,
    source text not null,
    amount numeric(10,2) not null check (amount > 0),
    received_at date not null,
    description text,
    created_at timestamptz not null default now()
);

drop function if exists public.get_course_financial_summary();

create or replace function public.get_course_financial_summary()
returns table (
    total_fee_payments numeric,
    total_extra_income numeric,
    total_income numeric,
    total_course_debt numeric,
    total_expenses numeric,
    current_balance numeric
)
language sql
stable
security definer
set search_path = public
as $$
    with payment_totals as (
        select
            fee_id,
            coalesce(sum(amount_paid), 0)::numeric as paid_total
        from public.payments
        group by fee_id
    ),
    fee_debt as (
        select
            coalesce(sum(greatest(f.amount - coalesce(pt.paid_total, 0), 0)), 0)::numeric as total_course_debt
        from public.fees f
        left join payment_totals pt on pt.fee_id = f.id
    )
    select
        coalesce((select sum(amount_paid) from public.payments), 0)::numeric as total_fee_payments,
        coalesce((select sum(amount) from public.income_entries), 0)::numeric as total_extra_income,
        (
            coalesce((select sum(amount_paid) from public.payments), 0)
            + coalesce((select sum(amount) from public.income_entries), 0)
        )::numeric as total_income,
        (select total_course_debt from fee_debt),
        coalesce((select sum(amount) from public.expenses), 0)::numeric as total_expenses,
        (
            coalesce((select sum(amount_paid) from public.payments), 0)
            + coalesce((select sum(amount) from public.income_entries), 0)
            - coalesce((select sum(amount) from public.expenses), 0)
        )::numeric as current_balance;
$$;

grant execute on function public.get_course_financial_summary() to authenticated;

alter table public.income_entries enable row level security;

drop policy if exists "income entries authenticated read" on public.income_entries;
drop policy if exists "income entries public read" on public.income_entries;
create policy "income entries authenticated read"
on public.income_entries for select
to authenticated
using (true);

drop policy if exists "treasurer manage income entries" on public.income_entries;
create policy "treasurer manage income entries"
on public.income_entries for all
to authenticated
using ((select public.is_treasurer()))
with check ((select public.is_treasurer()));

create index if not exists idx_income_entries_received_at
on public.income_entries(received_at);
